
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/Program Files/CLion 2025.2.1/bin/cmake/win/x64/share/cmake-4.1/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.26100 - AMD64
  -
    kind: "find-v1"
    backtrace:
      - "D:/Program Files/CLion 2025.2.1/bin/cmake/win/x64/share/cmake-4.1/Modules/CMakeMinGWFindMake.cmake:5 (find_program)"
      - "CMakeLists.txt:2 (project)"
    mode: "program"
    variable: "CMAKE_MAKE_PROGRAM"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "mingw32-make.exe"
    candidate_directories:
      - "D:/Program Files/CLion 2025.2.1/bin/mingw/bin/"
      - "C:/Windows/System32/HWAudioDriver/"
      - "C:/Windows/System32/"
      - "C:/Windows/"
      - "C:/Windows/System32/wbem/"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/"
      - "C:/Windows/System32/OpenSSH/"
      - "C:/Users/Administrator/AppData/Local/Microsoft/WindowsApps/"
      - "C:/Program Files/PuTTY/"
      - "C:/Program Files/Go/bin/"
      - "D:/Program Files/Minikube/"
      - "C:/Program Files/Git/cmd/"
      - "C:/Program Files/Docker/Docker/resources/bin/"
      - "C:/Users/bobro/AppData/Local/Microsoft/WindowsApps/"
      - "C:/Program Files/JetBrains/CLion 2024.3.2/bin/"
      - "C:/Users/bobro/AppData/Local/Programs/Microsoft VS Code/bin/"
      - "C:/Program Files/JetBrains/GoLand 2025.1.1/bin/"
      - "C:/Users/bobro/go/bin/"
      - "C:/Users/bobro/AppData/Local/JetBrains/Toolbox/scripts/"
      - "D:/Program Files/DataGrip 2025.2.1/bin/"
      - "D:/Program Files/GoLand 2025.2/bin/"
      - "D:/Program Files/CLion 2025.2.1/bin/"
      - "D:/Program Files/CLion 2025.2.1/bin/ninja/win/x64/"
      - "/REGISTRY-NOTFOUND/bin/"
      - "c:/MinGW/bin/"
      - "/MinGW/bin/"
      - "/REGISTRY-NOTFOUND/MinGW/bin/"
    searched_directories:
      - "D:/Program Files/CLion 2025.2.1/bin/mingw/bin/mingw32-make.exe.com"
    found: "D:/Program Files/CLion 2025.2.1/bin/mingw/bin/mingw32-make.exe"
    search_context:
      ENV{PATH}:
        - "D:\\Program Files\\CLion 2025.2.1\\bin\\mingw\\bin"
        - "C:\\Windows\\System32\\HWAudioDriver"
        - "C:\\Windows\\system32"
        - "C:\\Windows"
        - "C:\\Windows\\System32\\Wbem"
        - "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\Windows\\System32\\OpenSSH\\"
        - "C:\\Users\\Administrator\\AppData\\Local\\Microsoft\\WindowsApps"
        - "C:\\WINDOWS\\system32"
        - "C:\\WINDOWS"
        - "C:\\WINDOWS\\System32\\Wbem"
        - "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\WINDOWS\\System32\\OpenSSH\\"
        - "C:\\Program Files\\PuTTY\\"
        - "C:\\Program Files\\Go\\bin"
        - "D:\\Program Files\\Minikube"
        - "C:\\Program Files\\Git\\cmd"
        - "C:\\Program Files\\Docker\\Docker\\resources\\bin"
        - "C:\\Users\\bobro\\AppData\\Local\\Microsoft\\WindowsApps"
        - "C:\\Program Files\\JetBrains\\CLion 2024.3.2\\bin"
        - "C:\\Users\\bobro\\AppData\\Local\\Programs\\Microsoft VS Code\\bin"
        - "C:\\Program Files\\JetBrains\\GoLand 2025.1.1\\bin"
        - "C:\\Users\\bobro\\go\\bin"
        - "C:\\Users\\bobro\\AppData\\Local\\JetBrains\\Toolbox\\scripts"
        - "D:\\Program Files\\DataGrip 2025.2.1\\bin"
        - "D:\\Program Files\\GoLand 2025.2\\bin"
        - "D:\\Program Files\\CLion 2025.2.1\\bin"
        - "D:\\Program Files\\CLion 2025.2.1\\bin\\ninja\\win\\x64"
  -
    kind: "find-v1"
    backtrace:
      - "D:/Program Files/CLion 2025.2.1/bin/cmake/win/x64/share/cmake-4.1/Modules/CMakeDetermineCompiler.cmake:63 (find_program)"
      - "D:/Program Files/CLion 2025.2.1/bin/cmake/win/x64/share/cmake-4.1/Modules/CMakeDetermineCCompiler.cmake:64 (_cmake_find_compiler)"
      - "CMakeLists.txt:2 (project)"
    mode: "program"
    variable: "CMAKE_C_COMPILER"
    description: "C compiler"
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: false
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: false
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: false
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "cc"
      - "gcc"
      - "cl"
      - "bcc"
      - "xlc"
      - "icx"
      - "clang"
    candidate_directories:
      - "D:/Program Files/CLion 2025.2.1/bin/mingw/bin/"
      - "C:/Windows/System32/HWAudioDriver/"
      - "C:/Windows/System32/"
      - "C:/Windows/"
      - "C:/Windows/System32/wbem/"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/"
      - "C:/Windows/System32/OpenSSH/"
      - "C:/Users/Administrator/AppData/Local/Microsoft/WindowsApps/"
      - "C:/Program Files/PuTTY/"
      - "C:/Program Files/Go/bin/"
      - "D:/Program Files/Minikube/"
      - "C:/Program Files/Git/cmd/"
      - "C:/Program Files/Docker/Docker/resources/bin/"
      - "C:/Users/bobro/AppData/Local/Microsoft/WindowsApps/"
      - "C:/Program Files/JetBrains/CLion 2024.3.2/bin/"
      - "C:/Users/bobro/AppData/Local/Programs/Microsoft VS Code/bin/"
      - "C:/Program Files/JetBrains/GoLand 2025.1.1/bin/"
      - "C:/Users/bobro/go/bin/"
      - "C:/Users/bobro/AppData/Local/JetBrains/Toolbox/scripts/"
      - "D:/Program Files/DataGrip 2025.2.1/bin/"
      - "D:/Program Files/GoLand 2025.2/bin/"
      - "D:/Program Files/CLion 2025.2.1/bin/"
      - "D:/Program Files/CLion 2025.2.1/bin/ninja/win/x64/"
    searched_directories:
      - "D:/Program Files/CLion 2025.2.1/bin/mingw/bin/cc.com"
      - "D:/Program Files/CLion 2025.2.1/bin/mingw/bin/cc.exe"
      - "D:/Program Files/CLion 2025.2.1/bin/mingw/bin/cc"
      - "D:/Program Files/CLion 2025.2.1/bin/mingw/bin/gcc.com"
    found: "D:/Program Files/CLion 2025.2.1/bin/mingw/bin/gcc.exe"
    search_context:
      ENV{PATH}:
        - "D:\\Program Files\\CLion 2025.2.1\\bin\\mingw\\bin"
        - "C:\\Windows\\System32\\HWAudioDriver"
        - "C:\\Windows\\system32"
        - "C:\\Windows"
        - "C:\\Windows\\System32\\Wbem"
        - "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\Windows\\System32\\OpenSSH\\"
        - "C:\\Users\\Administrator\\AppData\\Local\\Microsoft\\WindowsApps"
        - "C:\\WINDOWS\\system32"
        - "C:\\WINDOWS"
        - "C:\\WINDOWS\\System32\\Wbem"
        - "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\WINDOWS\\System32\\OpenSSH\\"
        - "C:\\Program Files\\PuTTY\\"
        - "C:\\Program Files\\Go\\bin"
        - "D:\\Program Files\\Minikube"
        - "C:\\Program Files\\Git\\cmd"
        - "C:\\Program Files\\Docker\\Docker\\resources\\bin"
        - "C:\\Users\\bobro\\AppData\\Local\\Microsoft\\WindowsApps"
        - "C:\\Program Files\\JetBrains\\CLion 2024.3.2\\bin"
        - "C:\\Users\\bobro\\AppData\\Local\\Programs\\Microsoft VS Code\\bin"
        - "C:\\Program Files\\JetBrains\\GoLand 2025.1.1\\bin"
        - "C:\\Users\\bobro\\go\\bin"
        - "C:\\Users\\bobro\\AppData\\Local\\JetBrains\\Toolbox\\scripts"
        - "D:\\Program Files\\DataGrip 2025.2.1\\bin"
        - "D:\\Program Files\\GoLand 2025.2\\bin"
        - "D:\\Program Files\\CLion 2025.2.1\\bin"
        - "D:\\Program Files\\CLion 2025.2.1\\bin\\ninja\\win\\x64"
  -
    kind: "find-v1"
    backtrace:
      - "D:/Program Files/CLion 2025.2.1/bin/cmake/win/x64/share/cmake-4.1/Modules/CMakeDetermineCompilerId.cmake:462 (find_file)"
      - "D:/Program Files/CLion 2025.2.1/bin/cmake/win/x64/share/cmake-4.1/Modules/CMakeDetermineCompilerId.cmake:500 (CMAKE_DETERMINE_COMPILER_ID_WRITE)"
      - "D:/Program Files/CLion 2025.2.1/bin/cmake/win/x64/share/cmake-4.1/Modules/CMakeDetermineCompilerId.cmake:8 (CMAKE_DETERMINE_COMPILER_ID_BUILD)"
      - "D:/Program Files/CLion 2025.2.1/bin/cmake/win/x64/share/cmake-4.1/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/Program Files/CLion 2025.2.1/bin/cmake/win/x64/share/cmake-4.1/Modules/CMakeDetermineCCompiler.cmake:122 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    mode: "file"
    variable: "src_in"
    description: "Path to a file."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "CMakeCCompilerId.c.in"
    candidate_directories:
      - "D:/Program Files/CLion 2025.2.1/bin/cmake/win/x64/share/cmake-4.1/Modules/"
    found: "D:/Program Files/CLion 2025.2.1/bin/cmake/win/x64/share/cmake-4.1/Modules/CMakeCCompilerId.c.in"
    search_context:
      ENV{PATH}:
        - "D:\\Program Files\\CLion 2025.2.1\\bin\\mingw\\bin"
        - "C:\\Windows\\System32\\HWAudioDriver"
        - "C:\\Windows\\system32"
        - "C:\\Windows"
        - "C:\\Windows\\System32\\Wbem"
        - "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\Windows\\System32\\OpenSSH\\"
        - "C:\\Users\\Administrator\\AppData\\Local\\Microsoft\\WindowsApps"
        - "C:\\WINDOWS\\system32"
        - "C:\\WINDOWS"
        - "C:\\WINDOWS\\System32\\Wbem"
        - "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\WINDOWS\\System32\\OpenSSH\\"
        - "C:\\Program Files\\PuTTY\\"
        - "C:\\Program Files\\Go\\bin"
        - "D:\\Program Files\\Minikube"
        - "C:\\Program Files\\Git\\cmd"
        - "C:\\Program Files\\Docker\\Docker\\resources\\bin"
        - "C:\\Users\\bobro\\AppData\\Local\\Microsoft\\WindowsApps"
        - "C:\\Program Files\\JetBrains\\CLion 2024.3.2\\bin"
        - "C:\\Users\\bobro\\AppData\\Local\\Programs\\Microsoft VS Code\\bin"
        - "C:\\Program Files\\JetBrains\\GoLand 2025.1.1\\bin"
        - "C:\\Users\\bobro\\go\\bin"
        - "C:\\Users\\bobro\\AppData\\Local\\JetBrains\\Toolbox\\scripts"
        - "D:\\Program Files\\DataGrip 2025.2.1\\bin"
        - "D:\\Program Files\\GoLand 2025.2\\bin"
        - "D:\\Program Files\\CLion 2025.2.1\\bin"
        - "D:\\Program Files\\CLion 2025.2.1\\bin\\ninja\\win\\x64"
